name: Docker

on:
  workflow_call: 

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: curso-ci-go-main

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: uiratan
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: uiratan/go_ci:${{ github.ref_name }}